exclude: '^$'
fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
    args: ['--maxkb=1024']
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args: ['--markdown-linebreak-ext=md']
  - id: pretty-format-json
    args: ['--autofix', '--indent', '2', '--no-sort-keys']
    exclude: ^Pipfile
  - id: detect-private-key

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.47.0
  hooks:
  - id: terraform_fmt
  - id: terraform_validate
  #   -   id: terraform_docs_replace
  - id: terraform_tflint
    args: ['--args=--disable-rule=terraform_unused_declarations']
  - id: terraform_tfsec

- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
  - id: isort
    additional_dependencies: ["toml"]

- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
  - id: black
    additional_dependencies: ["toml"]

- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  -   id: flake8
